- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
  verbs:
    - get
    - list
    - update
    - watch
- apiGroups:
    - agents.lightrun.com
  resources:
    - clusteragentpools
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - agents.lightrun.com
  resources:
    - clusteragentpools/status
  verbs:
    - get
    - patch
    - update
